vich_uploader:
    db_driver: orm

    mappings:
        photos:
            uri_prefix: /images/photos
            upload_destination: "%kernel.project_dir%/public/images/photos"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        videos:
            uri_prefix: /images/videos
            upload_destination: "%kernel.project_dir%/public/images/videos"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        avatars:
            uri_prefix: /images/avatars
            upload_destination: "%kernel.project_dir%/public/images/avatars"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
